name: super40_academy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/slid1.jpg
    - assets/slid2.jpg
    - assets/slid3.jpg
    - assets/slid4.jpg
    - assets/teacher1.jpg
    - assets/teacher2.jpg
    - assets/teacher3.jpg
    - assets/teacher4.jpg
    - assets/teacher5.jpg
    - assets/teacher6.jpg
    - assets/teacher7.jpg
    - assets/teacher8.jpg
    - assets/teacher9.jpg
    - assets/teacher10.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
